config/routes.rb
Komanda::Application.routes.draw do
  root :to => 'parties#index'
  
  #match '/users' => 'static_pages#users'
  match '/stats' => 'static_pages#stats'

  match '/contact' => 'static_pages#contact'
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', :as => :signout
  
  match '/shares' => 'shares#index'

  match '/parties/rate', :controller => 'parties', :action => 'rate'
  match '/parties/join', :controller => 'parties', :action => 'join'
  match '/parties/unjoin', :controller => 'parties', :action => 'unjoin'

  match '/suggestions/star', :controller => 'suggestions', :action => 'star'
  match '/suggestions/unstar', :controller => 'suggestions', :action => 'unstar'

  resources :shares
  resources :comments

  resources :parties do
    resources :comments
  end
  
  resources :suggestions do
    resources :comments
  end
end

app/models/party.rb
class Party
  include Mongoid::Document
  include Mongoid::Slug
  include Mongoid::Timestamps
  include Mongoid::MultiParameterAttributes
    
  field :title
  field :description
  field :when, :type => DateTime
  field :flyer
  field :description
  field :address
  field :map
  field :pics, type: Array, default: []
  field :views, default: 0
  field :price, type: Float, default: 15.00
  field :ratings, type: Hash, default: {}
  field :going, type: Array, default: []
  slug  :title
  
  index({ id: 1})
  has_many :comments, as: :commentable, dependent: :destroy
  validates_presence_of :title, :description  

  def get_rating()
    if self.ratings.empty?
      return 0
    else
      avg = 0
      self.ratings.each_value do |value|
        avg += value.to_i
      end

      return avg / self.ratings.count.to_i
    end
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_filter :admin_user, only: [:create, :update, :destroy]
  before_filter :logged_in, only: [:rate, :join, :unjoin]
  # GET /parties
  # GET /parties.json
  def index
    @today = Time.now
     
    if params[:sidebar]
      @sidebar = true
      @skip = params[:skip].to_i
      @parties = Party.desc(:when).skip(@skip).limit(5).to_a
      @prev = Party.find(params[:prev])
      @skip += 5
      @done = Party.all.count <= @skip ? true : false

      if params[:extra]
        @extra = params[:extra]
        @parties.delete(Party.find(@extra))
      end

    elsif params[:skip]
      @skip = params[:skip].to_i
      @previous = Party.where(:when.lt => @today).skip(@skip).desc(:when).limit(4)
      @skip += 4
      @done = Party.where(:when.lt => @today).count <= @skip ? true : false
    else  
      @previous = Party.where(:when.lt => @today).desc(:when).limit(4)
      @upcoming = Party.where(:when.gt => @today).desc(:when)
      @suggestions = Suggestion.skip(@skip).limit(3).order_by(:vote_counter.desc, :comment_counter.desc, :created_at.desc)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    if params[:prev]
      @prev = Party.find(params[:prev])
    elsif params[:modal]
      @modal = true
    end

    @party = Party.find(params[:id])
    @party.inc(:views, 1)

    unless @prev || @modal  
      today = Time.now
      @upcoming = Party.where(:when.gte => today).desc(:when)
      @previous = Party.where(:when.lt => today).desc(:when).limit(4)
      # @parties = Party.all.desc(:when).limit(5).to_a

      unless @upcoming.include?(@party) || @previous.include?(@party)
        if @party.when > today
          @upcoming << @party
        else
          @previous << @party
        end
        @extra = @party.id  
      end
      
    end


    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /parties/new
  # GET /parties/new.json
  def new
    admin_user
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
    admin_user
    @party = Party.find(params[:id])
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(params[:party])
    @party.pics = (params[:party][:pics]).split

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render json: @party, status: :created, location: @party }
      else
        format.html { render action: "new" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parties/1
  # PUT /parties/1.json
  def update
    @party = Party.find(params[:id])
    @party.assign_attributes(params[:party])
    @party.pics = (params[:party][:pics]).split

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party = Party.find(params[:id])
    @party.destroy

    respond_to do |format|
      format.html { redirect_to parties_url }
      format.json { head :no_content }
    end
  end

  def rate
    if current_user.id.to_s == params[:user]
      @rating = params[:rating]

      @party = Party.find(params[:party])
      @party.ratings["#{current_user.id}"] = @rating
      @party.save

      @user = User.find(params[:user])
      @user.ratings["#{@party.id}"] = @rating
      @user.save
    end

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end  
  end

  def join
    @party = Party.find(params[:party])
    @party.going << current_user.id unless @party.going.include?(current_user.id)
    @party.save

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/parties_helper.rb
module PartiesHelper  
  
  def render_current_rating(rating)
    html = ""
    rating.times { html += "<i class='icon-star'></i>" }
    (5 - rating).times { html += "<i class='icon-star-empty'></i>" }
    raw html
  end

  def get_party_comments(party)
    if party.comments.count < 3
      party.comments
    else
      party.comments.skip(party.comments.count - 3)
    end
  end
  
  def render_view_party_comments_link(party)
    if party.comments.count <= 50
      link_to "View #{party.comments.count - 3} previous comments", 
              "/comments?party_id=#{party.id}",
              remote: true,
              id: "more_comments"
    else
      link_to "View previous comments",
              "/comments?party_id=#{party.id}&skip=#{party.comments.count - 50 - 3}",
              remote: true,
              id: "more_comments"
    end
  end
  
end

app/views/parties/_modal.html.erb
<div id="party-modal" class="modal fade hide">

	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="modal-title"><%= @party.title %> 
			<small><%= time_tag @party.when, format: "%B %e, %l:%M %P" %></small>
		</h3>
	</div>
	
	<div class="modal-body">
		
		<% if current_user && admin_user? %>
			<div>
		      <%= link_to "Edit", edit_party_path(@party), :class => 'btn btn-mini' %>
	          <%= link_to "Delete", party_path(@party),
	                      :method => :delete,
	                      :data => { :confirm => 'Are you sure?' },
	                      :class => 'btn btn-mini btn-danger' %>
			</div>
		<% end %>
		<p id="modal-description">
			<div class="span2">
				<%= link_to image_tag(@party.flyer, class: "img-polaroid flyer span2"), @party %>
				<div id="modal-pics">
					<% if @party.pics.count > 0 %>
						<%= link_to "View pictures", "#{party_path(@party)}#pictures" %> 
					<% end -%>
				</div>
			</div>
			<div id="rating-area">
				<% if current_user %>
						
					<div id="rate" val="<%= @party.get_rating %>">
						<% for i in 1..@party.get_rating %>
							<%= link_to image_tag("star.png", size: "35x0"),
								"/parties/rate?party=#{@party.id}&user=#{current_user.id}&rating=#{i}", 
								remote: true %>
						<% end -%>
						

						<% for i in 1 + @party.get_rating..5 %>
							<%= link_to image_tag("star_empty.png", size: "35x0"), 
								"/parties/rate?party=#{@party.id}&user=#{current_user.id}&rating=#{i}",
								remote: true %>
						<% end -%>
					</div> 
					<p><span id="rating-count" class="muted"><%= pluralize @party.ratings.count, "rating" %></span>

					<% if @party.ratings.include?("#{current_user.id}") %>
						<span id="voted" class="muted">
							 | You rating: <span id="user_rating">
							<%= pluralize(@party.ratings["#{current_user.id}"].to_i, "star") %></span>.
						</span>
					<% else %>
						<span id="voted" class="muted hide">
							 | You rating: <span id="user_rating"></span>
						</span>
					<% end -%>

				<% else %>
					<div id="rate">
						<% for i in 1..@party.get_rating %>
							<%= image_tag("star.png", size: "35x0") %>
						<% end -%>
						

						<% for i in 1 + @party.get_rating..5 %>
							<%= image_tag("star_empty.png", size: "35x0") %>
						<% end -%>
					</div>

					<p><span id="rating-count" class="muted"><%= pluralize @party.ratings.count, "rating" %></span>
					| <a href="#signin">Sign in</a> to rate.</p>
				<% end -%>
			</div>	

			<hr class="bs-docs-separator">

			<p class="muted">
				<% if current_user %>
					<% if @party.going.include?(current_user.id) %>
						<button id="join_button_<%= @party.id %>" class="btn btn-success disabled join-button">Going</button>
					<% elsif Time.now < @party.when %>
						<%= link_to "Join", 
							"#{parties_join_path}?party=#{@party.id}", 
							class: "btn btn-success join-button", id: "join_button_#{@party.id}", remote: true %>
					<% else %>
						<button id="join_button_<%= @party.id %>" class="btn btn-success disabled join-button">Join</button>
					<% end -%>
				<% else %>
					<a id="join_button_<%= @party.id %>" class="btn btn-success join-button" rel="popover" data-placement="bottom" 
							data-content="<div class='text-center'><%= render 'shared/signin' %></div>"
							data-original-title="Sign in with:">Join</a>
				<% end -%>
				<span id="going_counter_<%= @party.id %>"><%= pluralize @party.going.count, "person" %></span> going
			</p>

			<hr class="bs-docs-separator">

			<% unless @party.address.blank? %>
				<p><i class="icon-map-marker"></i><strong> Address</strong></p>
				<p><%= @party.address %></p>
			<% end %>

			<p><i class="icon-info-sign"></i><strong> Info</strong></p>
			<%= raw @party.description %>
		</p>	

		<div class="separator">
			<strong>Comments (<span id="comment_count"><%= @party.comments.count %></span>)</strong>
			
			<span id="more_comments" class="pull-right">
				<% if @party.comments.count > 3 %>
					<span id="loading-msg" class="muted" "data-loading-text"="loading...">showing</span>
					<% if @party.comments.count <= 50 %>
						<%= link_to("/comments?party_id=#{@party.id}",
							id: "more_comments_link",
							remote: true) do %>
							<span id="comments_loaded">3</span>/<span id="total_comments"><%= @party.comments.count %></span>
						<% end -%>
					<% else %>
						<%= link_to("/comments?party_id=#{@party.id}&skip=#{@party.comments.count - 50 - 3}",
							id: "more_comments_link",
							remote: true) do %>
							<span id="comments_loaded">3</span>/<span id="total_comments"><%= @party.comments.count %></span>
						<% end -%>
					<% end -%>
				<% end -%>
			</span>
		</div>

		<div id="comments">
			<% if @party.comments.count > 0 %>
				<% get_party_comments(@party).each do |comment| %>
					<%= render 'comments/comment', object: [@party, comment] %>
				<% end %>
			<% end %>
		</div>

		<div class="form">
			<% if current_user %>
				<%= render 'comments/form', object: @party %>
			<% else %>	
				<div id="signin" class="text-center">Sign in with <%= render 'shared/signin' %> to leave a comment.</div>
			<% end %>
		</div>
	</div>

	<div class="modal-footer">
		<div class="pull-right">
		<span class="label">Price: $<%= @party.price %></span>
		<span class="label label-important">Age: 21+</span>
	</div>
	</div>
</div>

app/views/parties/_party.html.erb
<li class="party span2">

	<article class="thumbnail">
		<% if current_user && admin_user? %>
			<div class="admin">
		      <%= link_to "Edit", edit_party_path(party), :class => 'btn btn-mini' %>
	          <%= link_to "Delete",
	                      party_path(party),
	                      :method => :delete,
	                      :data => { :confirm => 'Are you sure?' },
	                      :class => 'btn btn-mini btn-danger' %>
			</div>	
		<% end %>

		<div class="flyer">
			<%= link_to image_tag(party.flyer), party_path(party), class: "visible-desktop", remote: true %>
			<%= link_to image_tag(party.flyer), party_path(party), class: "visible-phone" %>
		</div>

		<h4><%= link_to party.title, party %></h4>

		<footer class="muted">
			<%= link_to("#{party_path(party)}#pictures") do %>
				<strong><small><%= pluralize(party.pics.count, "pic") %>
			<% end %>
			<span> | </span>
			<%= link_to("#{party_path(party)}#comments") do %>
				<%= pluralize(party.comments.count, "comment") %></small></strong>
			<% end %>
		</footer>

	</article>

</li>

app/views/parties/_party_full.html.erb
<div class="default">
	<div class="page-header">
		<% if current_user && admin_user? %>
			<div class="">
				<%= link_to "New", new_party_path, class: "btn btn-mini" %>
										
				<%= link_to "Edit", edit_party_path(object), class: "btn btn-mini" %>
								
				<%= link_to "Delete", party_path(object), class: "btn btn-danger btn-mini", :method => 'delete',
											              :data => { :confirm => 'Are you sure?' } %>
			</div>
		<% end -%>
		<div class="pull-right fb-like visible-desktop" 
 			data-send="false" data-layout="button_count" 
 			data-width="450" data-show-faces="true"></div>
	  	<h2><%= object.title %> <small><%= time_tag object.when, format: "%B %e, %l:%M %P" %></small></h2>
	</div>
	<%= image_tag object.flyer, class: "img-polaroid pull-left flyer span3" %>

	<% if current_user %>				
		<div id="rate" val="<%= @party.get_rating %>">
			<% for i in 1..@party.get_rating %>
				<%= link_to image_tag("star.png", size: "35x0"),
					"/parties/rate?party=#{@party.id}&user=#{current_user.id}&rating=#{i}", 
					remote: true %>
			<% end -%>
			

			<% for i in 1 + @party.get_rating..5 %>
				<%= link_to image_tag("star_empty.png", size: "35x0"), 
					"/parties/rate?party=#{@party.id}&user=#{current_user.id}&rating=#{i}",
					remote: true %>
			<% end -%>
		</div> 
		<p>
			<span id="rating-count" class="muted"><%= pluralize @party.ratings.count, "rating" %></span>		

			<% if current_user && @party.ratings.include?("#{current_user.id}") %>
				<span id="voted" class="muted">
					 | Your rating: <span id="user_rating">
					<%= pluralize(@party.ratings["#{current_user.id}"].to_i, "star") %></span>.
				</span>
			<% else %>
				<span id="voted" class="muted hide">
					 | Your rating: <span id="user_rating"></span>
				</span>
			<% end -%>
		</p>

	<% else %>
		<div id="rate">
			<% for i in 1..@party.get_rating %>
				<%= image_tag("star.png", size: "35x0") %>
			<% end -%>

			<% for i in 1 + @party.get_rating..5 %>
				<%= image_tag("star_empty.png", size: "35x0") %>
			<% end -%> 
		</div>
		<p class="muted">
			<span id="rating-count"><%= pluralize @party.ratings.count, "rating" %> | </span>
			<a href="#signin">Sign in</a> to rate.
		</p>
	<% end -%>

	<hr>
	
	<p class="muted">
		<% if current_user %>
			<% if object.going.include?(current_user.id) %>
				<button id="join_button_<%= @party.id %>" class="btn btn-success disabled join-button">Going</button>
			<% elsif Time.now < object.when %>
				<%= link_to "Join", 
					"#{parties_join_path}?party=#{object.id}", 
					class: "btn btn-success join-button", id: "join_button_#{@party.id}", remote: true %>
			<% else %>
				<button id="join_button_<%= @party.id %>" class="btn btn-success disabled join-button">Join</button>
			<% end -%>
		<% else %>
			<a id="join_button_<%= @party.id %>" class="btn btn-success join-button" rel="popover" data-placement="right" 
					data-content="<div class='text-center'><%= render 'shared/signin' %></div>"
					data-original-title="Sign in with:">Join</a>
		<% end -%>
		<span id="going_counter_<%= @party.id %>"><%= pluralize object.going.count, "person" %></span> going
	</p>

	<hr class="bs-dosc-separator">
	
	<% unless object.address.blank? %>
		<p><i class="icon-map-marker"></i><strong> Address</strong></p>
		<p><%= object.address %></p>
	<% end -%>

	<p><i class="icon-info-sign"></i><strong> Info</strong></p>
	<%= raw object.description %>
	<span class="label">Price: $<%= object.price %></span>
	<span class="label label-important">Age: 21+</span>

	<!-- pictures -->
	<div class="visible-desktop">
		<% if object.pics.count > 0 %>
			<div class="separator">
				<strong> Picutres (<%= object.pics.count %>)</strong>

				<% if object.pics.count > 9 %>
					<span class="pull-right">
						<span class="muted" id="pics_loading_msg" "data-loading-text"="loading..." %>showing </span>
						<a href="#" id="show_pictures">9/<%= object.pics.count %></a>
					</span>
				<% end -%>
			</div>

			<ul class="thumbnails" id="pictures">
				<% if object.pics.count > 9 %>
					<% for i in 0..8 %>
						<li class="span2">
							<%= link_to image_tag(object.pics[i]),
								"#picture-modal",
								"data-toggle"=>"modal",
								class: "thumbnail" %>
						</li>
					<% end -%>
					
					<% for i in 9..object.pics.count - 1 %>
						<li class="span2 hide">
							<%= link_to image_tag(object.pics[i]),
								"#picture-modal",
								"data-toggle"=>"modal",
								class: "thumbnail" %>
						</li>
					<% end -%>
				<% else %>
					<% object.pics.each do |pic| %>
						<li class="span2">
							<%= link_to image_tag(pic),
								"#picture-modal",
								"data-toggle"=>"modal",
								class: "thumbnail" %>
						</li>

					<% end -%>
				<% end -%>
			</ul>
			<div id="picture-modal" class="modal hide hidden-phone" data-keyboard="true">	
				<div class="modal-body">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<p>Image <span id="picture_index">1</span>/<span id="total"><%= object.pics.count %></span></p>
					<%= image_tag "", class: "img-rounded", id: "modal-picture" %>
							
					<a id="prev-button" class="carousel-control left" href="" data-slide="prev">&lsaquo;</a>
			  		<a id="next-button" class="carousel-control right" href="" data-slide="next">&rsaquo;</a>
				</div>
			</div>
		<% end -%>
	</div>

	<div class="separator">
		<strong>Comments (<span id="comment_count"><%= object.comments.count %></span>)</strong>
		
		<span id="more_comments" class="pull-right">
			<% if object.comments.count > 3 %>
				<span id="loading-msg" class="muted" "data-loading-text"="loading...">showing</span>
				<% if object.comments.count <= 50 %>
					<%= link_to("/comments?party_id=#{object.id}",
						id: "more_comments_link",
						remote: true) do %>
						<span id="comments_loaded">3</span>/<span id="total_comments"><%= object.comments.count %></span>
					<% end -%>
				<% else %>
					<%= link_to("/comments?party_id=#{object.id}&skip=#{object.comments.count - 50 - 3}",
						id: "more_comments_link",
						remote: true) do %>
						<span id="comments_loaded">3</span>/<span id="total_comments"><%= object.comments.count %></span>
					<% end -%>
				<% end -%>
			<% end -%>
		</span>
	</div>
	
	<div id="comments">	
		<% if object.comments.count > 0 %>
			<% get_party_comments(object).each do |comment| %>
				<%= render 'comments/comment', object: [object, comment] %>
			<% end %>
		<% end %>	
	</div>

	<div class="form">
		<% if current_user %>
			<%= render 'comments/form', object: object %>
		<% else %>
			<a rel="popover" data-placement="right" 
					data-content="<div class='text-center'><%= render 'shared/signin' %></div>"
					data-original-title="Sign in with:">Sign in</a>
			to leave a comment.
		<% end %>
	</div>
</div>

app/views/parties/_party_preview.html.erb
<div class="party-preview">
		<%= link_to (image_tag object.flyer, class: "img-polaroid span3 pull-left"), object %>

		<!-- <div class="span4"> -->
			<h3><%= object.title %> <small><%= time_tag object.when, format: "%B %e, %l:%M %P" %></small></h3>
			<hr class="bs-dosc-separator">
			<p class="muted">
				<% if current_user %>
					<% if object.going.include?(current_user.id) %>
						<button id="join_button_<%= object.id %>" class="btn btn-success disabled join-button">Going</button>
					<% else %>
						<%= link_to "Join", 
							"#{parties_join_path}?party=#{object.id}", 
							class: "btn btn-success join-button", id: "join_button_#{object.id}", remote: true %>
					<% end -%>
				<% else %>
					<a id="join_button" class="btn btn-success join-button" rel="popover" data-placement="right" 
							data-content="<div class='text-center'><%= render 'shared/signin' %></div>"
							data-original-title="Sign in with:">Join</a>
				<% end -%>
				<span id="going_counter_<%= object.id %>"><%= pluralize object.going.count, "person" %></span> going
			</p>
			<hr class="bs-dosc-separator">
			
			<%= raw (truncate object.description, length: 400) %> <%= link_to "continue", object %>
		<!-- </div> -->
		<div class="pull-right">
			<span>
				<%= link_to("#{party_path(object)}#comments") do %>
					<%= pluralize(object.comments.count, "Comment") %>
				<% end -%>
			</span>
			<span class="label">Price: $<%= object.price %></span>
			<span class="label label-important">Age: 21+</span>
		</div>
</div>

app/views/parties/_sidebar_party.html.erb
<article id="<%= object[0].id %>" class="thumbnail <%= "active" unless object[0].id != object[1] %>">
	<% if object[1] == "x" %>
		<%= link_to(party_path(object[0])) do %>
			<div class="flyer">
				<%= image_tag(object[0].flyer) %>
			</div>

			<h5><%= object[0].title %></h5>

			<footer>
				<small class="">
					<%= pluralize(object[0].pics.count, "pic") %> | <%= pluralize(object[0].comments.count, "comment") %>
<!-- 					<i class="icon-picture"></i> <%= object[0].pics.count %>
					<span class="muted">-</span>
					<i class="icon-comment"></i> <%= object[0].comments.count %> -->
				</small>
			</footer>
		<% end -%>
	<% else %>
		<%= link_to(party_path(object[0]) + "?prev=#{object[1]}", remote: true) do %>
			<div class="flyer">
				<%= image_tag(object[0].flyer) %>
			</div>

			<h5><%= object[0].title %></h5>

			<footer>
				<small class="">
					<%= pluralize(object[0].pics.count, "pic") %> | <%= pluralize(object[0].comments.count, "comment") %>
					<!-- <i class="icon-picture"></i> <%= object[0].pics.count %>
					<span class="muted">-</span>
					<i class="icon-comment"></i> <%= object[0].comments.count %> -->
				</small>
			</footer>	
		<% end -%>
	<% end -%>	
</article>

app/views/parties/edit.html.erb
<%- model_class = Party -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/parties/index.html.erb
<div class="row">
	<div class="span8">
		<div class="pull-right fb-like visible-desktop" data-send="false" data-layout="button_count" data-width="450" data-show-faces="true"></div>
		<h2>Upcoming events</h2>

		<% if current_user && admin_user? %>
			<p><%= link_to "New event", new_party_path, class: "btn btn-primary btn-large" %></p>
		<% end -%>

		<% if @upcoming.count > 0 %>
			<% @upcoming.each do |event| %>
				<%= render 'party_preview', object: event %>
			<% end -%>
		<% else %>			
			<div class="lead">
				We are planning our next event.
				Have a suggestion? <%= link_to "Let us know!", suggestions_path %> Or <%= link_to "share", shares_path %> an event your are going to!
			</div>
		<% end -%>

		<h2>Previous events</h2>	

		<ul id="parties" class="thumbnails">
			<%= render @previous %>		
		</ul>


		<% if @previous.count >= 5 %>
			<p><%= link_to "More", "/parties?skip=4", id: "more", class: "more", "data-loading-text"=>"Loading...", remote: true %></p>
		<% end %>

		<div id="_modal">
		</div>
	</div>

	<aside class="span4 visible-desktop parties-sidebar aside">
		<% if @upcoming.count > 0 %>
			<p class="lead">
				Have a great idea for a party but too busy to organize it all on your own? Suggest the party here and we just might make it a reality!
			</p>

			<p class="text-center">
				<% if @suggestions.count > 0 %>
					<%= link_to "Suggest an event", suggestions_path, class: "btn btn-primary btn-large" %>
				<% end -%>
			</p>
		<% end -%>

		<hr>

		<%= render @suggestions %>
		
		<%= link_to "More", suggestions_path %>

 	</aside>
</div>

app/views/parties/join.js.erb
$("#join_button_<%= @party.id %>").addClass("disabled").text("Going").attr("href", "")
$("#going_counter_<%= @party.id %>").text("<%= pluralize @party.going.count, 'person' %>")

app/views/parties/new.html.erb
<%- model_class = Party -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/parties/show.html.erb
<article class="row">
	<article id="content" class="span8">
		<%= render "parties/party_full", object: @party %>
	</article>

	<aside id="index" class="span4 visible-desktop sidebar aside">
		<p class="lead">Have a great idea for a party but too busy to organize it all on your own? Suggest the party here and we just might make it a reality!
		</p>
		<p class="text-center">
			<%= link_to "Suggest an event", suggestions_path, class: "btn btn-primary btn-large" %>
		</p>

		<hr class="bs-docs-separator">

		<% if @upcoming.count > 0 %>
			<p class="lead muted">Upcoming events</p>
			<ul class="thumbnails" id="upcoming">
				<% @upcoming.each do |party| %>
					<li class="scroll"><%= render 'parties/sidebar_party', object: [party, @party.id] %></li>
				<% end %>
			</ul>	
		<% end %>
		
		<% if @previous.count > 0 %>
			<p class="lead muted">Previous events</p>
			<ul class="thumbnails" id="previous">
				<% @previous.each do |party| %>
					<li class="scroll"><%= render 'parties/sidebar_party', object: [party, @party.id] %></li>
				<% end %>
			</ul>	
		<% end %>
		
		<p>
			<% if @extra %>
				<%= link_to("#{parties_path}?sidebar=true&skip=5&extra=#{@extra}&prev=#{@party.id}", 
					class: "more",
					id: "more", 
					"data-loading-text"=>"Loading...", 
					remote: true) do %>
					More
				<% end -%>
			<% else %>
				<%= link_to("#{parties_path}?sidebar=true&skip=5&prev=#{@party.id}", 
					class: "more", 
					id: "more",
					"data-loading-text"=>"Loading...",
					remote: true) do %>
					More
				<% end -%>
			<% end -%>
		</p>
	</aside>
</article>