config/routes.rb
Komanda::Application.routes.draw do
  root :to => 'parties#index'
  
  #match '/users' => 'static_pages#users'
  match '/stats' => 'static_pages#stats'

  match '/contact' => 'static_pages#contact'
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', :as => :signout
  
  match '/shares' => 'shares#index'

  match '/parties/rate', :controller => 'parties', :action => 'rate'
  match '/parties/join', :controller => 'parties', :action => 'join'
  match '/parties/unjoin', :controller => 'parties', :action => 'unjoin'

  match '/suggestions/star', :controller => 'suggestions', :action => 'star'
  match '/suggestions/unstar', :controller => 'suggestions', :action => 'unstar'

  resources :shares
  resources :comments

  resources :parties do
    resources :comments
  end
  
  resources :suggestions do
    resources :comments
  end
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActionView::Helpers::SanitizeHelper
  
  field :content
  
  index({ id: 1})
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  validate :valid_comment
  
  private 
    
    def valid_comment
      strip_whitespace_and_tags
      
      unless self.content && self.user_id
        errors.add :base, "Comment cannot be blank."  
      end
    end

    def strip_whitespace_and_tags
      if self.content
        self.content = strip_tags(self.content.strip)
        if self.content.empty?
          self.content = nil
        end
      end
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :admin_user, only: :destroy
  
  def create
    unless spam?
        
      if params[:party_id]
        @party = Party.find(params[:party_id])
        @comment = @party.comments.create(params[:comment]) 
        @comment.user_id = current_user.id
        @comment.save     
        @comment_count = @party.comments.count
      else
        @suggestion = Suggestion.find(params[:suggestion_id])
        @comment = @suggestion.comments.create(params[:comment])
        @comment.user_id = current_user.id
        @comment.save
        @suggestion.inc(:comment_counter, 1)
      end
    end
    # redirect_to :back
    respond_to do |format|
      format.js
    end
  end

  def destroy
    if (params[:party_id])
      @party = Party.find(params[:party_id])
      @comment = @party.comments.find(params[:id])
      @comment.destroy
    else
      @suggestion = Suggestion.find(params[:suggestion_id])
      @comment = @suggestion.comments.find(params[:id])
      @comment.destroy
      @suggestion.inc(:comment_counter, -1)
    end

    respond_to do |format|
      format.js
    end
  end
  
  def index
    default_limit = 3
    comment_limit = 50

    if (params[:suggestion_id])
      @suggestion = Suggestion.find(params[:suggestion_id]) 
      
      if params[:skip]
        # View more comments
        @skip = params[:skip].to_i
        @comments = @suggestion.comments.skip(@skip).limit(comment_limit)
        
        if @skip - comment_limit < 0
          @limit = @skip
          @skip = 0
        else
          @skip -= comment_limit
        end
      elsif params[:limit]
        @comments = @suggestion.comments.limit(params[:limit])
        @done = true
      else
        # View all comments
        @comments = @suggestion.comments.limit(@suggestion.comments.count - default_limit)
      end
    else
      @party = Party.find(params[:party_id])

      if params[:skip]
        # View more comments
        @skip = params[:skip].to_i
        @comments = @party.comments.skip(@skip).limit(comment_limit)
        
        if @skip - comment_limit < 0
          @limit = @skip
          @skip = 0
        else
          @skip -= comment_limit
        end
      elsif params[:limit]
        @comments = @party.comments.limit(params[:limit])
        @done = true
      else
        # View all comments
        @comments = @party.comments.limit(@party.comments.count - default_limit)
      end
      
    end
    
    respond_to do |format|
      format.js
    end
  end
  
  private
    def spam?
      time = Time.now
      
      count = current_user.comments.count
      if count >= 2
        if time - current_user.comments[count - 2].created_at < 3.seconds
          return true
        end
      end
      return false
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<article id="<%= object[1].id %>" class="media">
	<% if current_user && admin_user? %>
		<%= link_to "×", party_comment_path(object[0], object[1]), class: "close", method: :delete, remote: true %>
	<% end %>

	<%= link_to image_tag(object[1].user.img_url, 
		size: "40x0", class: "img-rounded"), object[1].user.profile_url, class: "pull-left" %>

	<div class="media-body">
		<div class="media-heading">
		<%= link_to object[1].user.name, object[1].user.profile_url %>
		<small class="muted"><%= time_ago_in_words(object[1].created_at) %> ago</small>
	</div>
	<%= object[1].content %>
	</div>
</article>

<!-- <div class="comment-separator"></div> -->

app/views/comments/_form.html.erb
<div class="media">
	<div class="pull-left">
		<%= link_to image_tag(current_user.img_url, class: "img-rounded", size: "40x0"),
			current_user.profile_url %>
	</div>

	<div class="media-body">
		<%= form_for [object, Comment.new], remote: true do |f| %>

			<%= f.text_area :content, rows: 2, class: "span5", placeholder: "Write a comment..." %>
			<div id="error" class="text-error hide">Comment cannot be blank.</div>
			<%= f.submit "Post", :class => 'btn btn-primary', id: "post_button", class: "hide" %>

		<% end %>
	</div>
</div>

	
	

app/views/comments/_suggestion_comment.html.erb
<article class="media" id="<%= object[1].id %>">
	
	<% if current_user && admin_user? %>
		<%= link_to "×", suggestion_comment_path(object[0], object[1]), 
			class: "close", method: :delete, remote: true %>
	<% end %>

	<%= link_to image_tag(object[1].user.img_url, 
		size: "40x0", class: "img-rounded"), object[1].user.profile_url, class: "pull-left" %>

	<div class="media-body">
		<div class="media-heading">
		<%= link_to object[1].user.name, object[1].user.profile_url %>
		<small class="muted"><%= time_ago_in_words(object[1].created_at) %> ago</small>
		</div>
		<%= object[1].content %>
	</div>
</article>

app/views/comments/_suggestion_comment_form.html.erb
<div class="media">
	<div class="pull-left">
		<%= link_to image_tag(current_user.img_url, class: "img-rounded", size: "40x40"),
			current_user.profile_url %>
	</div>

	<div class="media-body">
		<%= form_for [object, Comment.new], html: { id: "form_for_#{object.id}" }, remote: true do |f| %>
			<%= f.text_area :content, rows: 2, placeholder: "Write a comment...",
				class: "comment_content span6",
				id: "comment_content_#{object.id}" %>
			<div id="error_<%= object.id %>" class="text-error hide">Comment cannot be blank.</div>
			<%= f.submit "Post", class: "hide post_button", id: "post_button_#{object.id}" %>
		<% end %>
	</div>
</div>

app/views/comments/create.js.erb
<% if @spam %>

<% else %>
	<% if @comment.errors.empty? %>
		<% if @party %>
			$('#comments').append("<%= escape_javascript(render 'comments/comment', object: [@party, @comment]) %>")
			$('#comment_count').text("<%= @party.comments.count %>")
			$('#comments_loaded').text(parseInt($('#comments_loaded').text()) + 1)
			$('#total_comments').text("<%= @party.comments.count %>")
			$('#comment_content').attr("value", "")
			$('#error').hide()
		<% else %>
			<% if @suggestion.comments.count == 1 %>
				$('#dummy_<%= @suggestion.id %>').append("<%= escape_javascript(render 'comments/comment', object: [@suggestion, @comment]) %>")
			<% else %>
				$('#<%= @suggestion.id %>_comments').append("<%= escape_javascript(render 'comments/suggestion_comment', object: [@suggestion, @comment]) %>")
			<% end %>
			
			$('#comment_count_<%= @suggestion.id %>').text("<%= @suggestion.comment_counter %>")

			$('#showing_<%= @suggestion.id %>').text(parseInt($('#showing_<%= @suggestion.id %>').text()) + 1)
			$('#comment_total_<%= @suggestion.id %>').text(parseInt($('#comment_total_<%= @suggestion.id %>').text()) + 1)
		
			$('#<%= @suggestion.id %> textarea').attr("value", "")
			$('#error_<%= @suggestion.id %>').hide()
		<% end %>
	<% else %>
		<% if @party %>
			$('#error').show()
			$('#comment_content').attr("value", "")
		<% else %>
			$('#error_<%= @suggestion.id %>').show()
			$('#<%= @suggestion.id %> textarea').attr("value", "")
			<% end %>
	<% end %>
<% end %>

app/views/comments/destroy.js.erb
$("#<%= @comment.id %>").fadeOut(100, function(){ $(this).remove();});

<% if @party %>
	$('#comment_count').text("<%= @party.comments.count %>")
	$('#comments_loaded').text(parseInt($('#comments_loaded').text()) - 1)
	$('#total_comments').text("<%= @party.comments.count %>")
<% else %>
	$('#comment_count_<%= @suggestion.id %>').text("<%= @suggestion.comment_counter %>")
	$('#showing_<%= @suggestion.id %>').text(parseInt($('#showing_<%= @suggestion.id %>').text()) - 1)
	$('#comment_total_<%= @suggestion.id %>').text(parseInt($('#comment_total_<%= @suggestion.id %>').text()) - 1)
<% end %>

app/views/comments/index.js.erb
<% if @party %>
	var loaded_comments = $("<div class='loaded_comments_<%= @party.id %>'></div>")
	
	<% @comments.each do |comment| %>
		loaded_comments.append("<%= escape_javascript(render 'comments/comment', object: [@party, comment]) %>")
	<% end %>
	
	$('#comments').prepend(loaded_comments)
	$("#loading-msg").button("reset")

	<% if @skip && @limit %>
		$('#comments_loaded').text(parseInt($('#comments_loaded').text()) + 50)
		$('#more_comments_link').attr("href", "/comments?party_id=<%= @party.id %>&limit=<%= @limit %>")
	<% elsif @skip %>		
		$('#comments_loaded').text(parseInt($('#comments_loaded').text()) + 50)
		$('#more_comments_link').attr("href", "/comments?party_id=<%= @party.id %>&skip=<%= @skip %>")
	<%# elsif @done %>
		// $('#comments_loaded').text("<%= @party.comments.count %>")
		// $('#more_comments_link').html("<span class='muted'><%=@party.comments.count %>/<%=@party.comments.count %></span>")
	<% else %>
		// $('#comments_loaded').text("<%= @party.comments.count %>")
		// $('#more_comments_link').html("<span class='muted'><%=@party.comments.count %>/<%=@party.comments.count %></span>")
		$('#more_comments').html("<span class='muted'>showing <%=@party.comments.count %>/<%=@party.comments.count %></span>")
	<% end %>
<% else %>
	var loaded_comments = $("<div class='loaded_comments_<%= @suggestion.id %>' id='loaded_comments_<%= @suggestion.id %>'></div>")
	
	<% @comments.each do |comment| %>
		loaded_comments.append("<%= escape_javascript(render 'comments/comment', object: [@suggestion, comment]) %>")
	<% end %>
	
	$('#<%= @suggestion.id %>_comments').prepend(loaded_comments)
	$("#<%= @suggestion.id %>-loading-msg").button('reset')
	// $('#<%= @suggestion.id %> article:first').prepend(loaded_comments)
	
	<% if @skip && @limit %>
		$('#showing_<%= @suggestion.id %>').text(parseInt($('#showing_<%= @suggestion.id %>').text()) + 50)
		$('#load_more_comments_<%= @suggestion.id %>').attr("href", "/comments?suggestion_id=<%= @suggestion.id %>&limit=<%= @limit %>")
	<% elsif @skip %>		
		$('#showing_<%= @suggestion.id %>').text(parseInt($('#showing_<%= @suggestion.id %>').text()) + 50)
		$('#load_more_comments_<%= @suggestion.id %>').attr("href", "/comments?suggestion_id=<%= @suggestion.id %>&skip=<%= @skip %>")
	<% else %>
		$("#<%= @suggestion.id %>-loading-msg").parent().html("<span class='muted'>showing <%= @suggestion.comments.count %>/<%= @suggestion.comments.count %></span>")
	<% end %>
<% end %>