config/routes.rb
Komanda::Application.routes.draw do
  root :to => 'parties#index'
  
  #match '/users' => 'static_pages#users'
  match '/stats' => 'static_pages#stats'

  match '/contact' => 'static_pages#contact'
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', :as => :signout
  
  match '/shares' => 'shares#index'

  match '/parties/rate', :controller => 'parties', :action => 'rate'
  match '/parties/join', :controller => 'parties', :action => 'join'
  match '/parties/unjoin', :controller => 'parties', :action => 'unjoin'

  match '/suggestions/star', :controller => 'suggestions', :action => 'star'
  match '/suggestions/unstar', :controller => 'suggestions', :action => 'unstar'

  resources :shares
  resources :comments

  resources :parties do
    resources :comments
  end
  
  resources :suggestions do
    resources :comments
  end
end

app/models/suggestion.rb
class Suggestion
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActionView::Helpers::SanitizeHelper
  
  field :location
  field :music
  field :games
  field :food_drinks
  field :other
  field :vote_counter, default: 0
  field :votes, type: Array, default: []
  field :comment_counter, default: 0
  
  index({ id: 1})
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user
  attr_accessible :location, :music, :games, :food_drinks, :other, :vote_counter, :votes
  validate :valid_suggestion
  
  private
  
    def valid_suggestion
      strip_whitespace_and_tags
      
      unless self.location || self.music || self.games || self.food_drinks || self.other
        errors.add :base, "One of the fields must be filled out."  
      end
    end
    
    def strip_whitespace_and_tags
      if self.location
        self.location = strip_tags(self.location.strip)
        if self.location.empty?
          self.location = nil
        end
      end

      if self.music
        self.music = strip_tags(self.music.strip)
        if self.music.empty?
          self.music = nil
        end
      end

      if self.games
        self.games = strip_tags(self.games.strip)
        if self.games.empty?
          self.games = nil
        end
      end

      if self.food_drinks
        self.food_drinks = strip_tags(self.food_drinks.strip)
        if self.food_drinks.empty?
          self.food_drinks = nil
        end
      end

      if !self.other.nil?
        self.other = strip_tags(self.other.strip)
        if self.other.empty?
          self.other = nil
        end
      end
    end  
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController

  before_filter :admin_user, only: [:destroy]
  before_filter :logged_in, only: [:star, :unstar, :create]
  
  def index
    suggestions_limit = 10 
    today = Time.now
    
    @suggestion = Suggestion.new
    @skip = (params[:skip].nil? ? 0 : params[:skip].to_i)
    @replace = (@skip == 0 ? true : false)
    @sort = params[:sort]
    @more = params[:more]
    
    if @sort.nil? || @sort == "date"
      @suggestions = Suggestion.skip(@skip).limit(suggestions_limit).desc(:created_at)
      @upcoming = Party.where(:when.gte => today).desc(:when).limit(3)
      @previous = Party.where(:when.lt => today).desc(:when).limit(3)
    elsif @sort == "votes"
      @suggestions = Suggestion.skip(@skip).limit(suggestions_limit).order_by(:vote_counter.desc, :comment_counter.desc, :created_at.desc)
    elsif @sort == "comments"
      @suggestions = Suggestion.skip(@skip).limit(suggestions_limit).order_by(:comment_counter.desc,:vote_counter.desc, :created_at.desc)
    end
    
    @skip += suggestions_limit
    @done = (@skip >= Suggestion.count ? true : false)
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @suggestion = Suggestion.new
  end

  def create 
    unless spam? 
      if current_user
        @suggestion = current_user.suggestions.create(params[:suggestion])
        @count = Suggestion.count
      end

      respond_to do |format|
        format.html { redirect_to suggestions_path }
        format.js
      end
    end
  end
  
  def edit
    if current_user
      @suggestion = Suggestion.find(params[:id])
      
      unless @suggestion.votes.include?(current_user.id)
        @suggestion.votes << current_user.id
        @suggestion.inc(:vote_counter, 1)
        @suggestion.save
        current_user.votes << @suggestion.id
        current_user.save
      end
      
      respond_to do |format|
        format.js
      end
    end
  end

  def destroy
    @suggestion = Suggestion.find(params[:id])    
    @suggestion.destroy unless @suggestion.nil?
    @count = Suggestion.count
    
    respond_to do |format|
      format.js
    end
  end

  def star
    @suggestion = Suggestion.find(params[:suggestion])
    unless @suggestion.votes.include?(current_user.id)
      @suggestion.votes << current_user.id
      @suggestion.inc(:vote_counter, 1)
      @suggestion.save
      current_user.votes << @suggestion.id
      current_user.save
    end
    
    respond_to do |format|
      format.js
    end
  end

  def unstar
    @suggestion = Suggestion.find(params[:suggestion])
    @suggestion.votes.delete(current_user.id)
    @suggestion.inc(:vote_counter, -1)
    @suggestion.save
    current_user.votes.delete(@suggestion.id)
    current_user.save

    respond_to do |format|
      format.js
    end
  end

  private
      
      def spam?
         time = Time.now

         count = current_user.suggestions.count
         if count >= 2
            if time - current_user.suggestions[count - 2].created_at < 3.seconds
               return true
            end
         end
         
         return false
      end
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
  
  def get_comments_for_suggestion(suggestion)
    if suggestion.comments.count <= 3
      comments = suggestion.comments
    else
      comments = suggestion.comments.skip(suggestion.comments.count - 3)
    end
  end
  
  def render_view_suggestion_comments_link(suggestion)
    if suggestion.comments.count > 3
      
      if suggestion.comments.count <= 50
        link_to "View #{suggestion.comments.count - 3} previous comments", 
                "/comments?suggestion_id=#{suggestion.id}",
                remote: true,
                id: "load_more_comments_#{suggestion.id}",
                class: "visible-desktop"
      else
        link_to "View previous comments",
                "/comments?suggestion_id=#{suggestion.id}&skip=#{suggestion.comments.count - 50 - 3}",
                remote: true,
                id: "load_more_comments_#{suggestion.id}",
                class: "visible-desktop"
      end
    end
  end
end

app/views/suggestions/_form.html.erb
<% if current_user %>
	<%= form_for @suggestion, html: { class: "default" } do |f| %>		
			
			<div id="suggestion_form_error" class="control-group hide">
				<div class="controls">
					<span class="text-error">At least one of the fields needs to be filled out.</span>
			   </div>
			</div>
			
			<div class="control-group">
			    <%= f.label(:class => 'control-label') do %>
			    	<i class="icon-map-marker"></i> Location
			    <% end -%>
			    <div class="controls">
			    	<%= f.text_area :location, rows: 2, maxlength: 2000, class: "span6" %> 
			    </div>
			</div>
			
			<div class="control-group">
			    <%= f.label(:class => 'control-label') do %>
			    	<i class="icon-music"></i> Music
			    <% end -%>
			    <div class="controls">
			    	<%= f.text_area :music, rows: 2, maxlength: 2000, class: "span6" %> 
			    </div>
			</div>
			
			<div class="control-group">
			    <%= f.label(:class => 'control-label') do %>
			    	<i class="icon-star"></i> Games
			    <% end -%>
			    <div class="controls">
			    	<%= f.text_area :games, rows: 2, maxlength: 2000, class: "span6" %> 
			    </div>
			</div>
			
			<div class="control-group">
			    <%= f.label(:class => 'control-label') do %>
			    	<i class="icon-glass"></i> Food/Drinks
			    <% end -%>
			    <div class="controls">
			    	<%= f.text_area :food_drinks, rows: 2, maxlength: 2000, class: "span6" %> 
			    </div>
			</div>
			
			<div class="control-group">
			    <%= f.label(:class => 'control-label') do %>
			    	<i class="icon-list-alt"></i> Other
			    <% end -%>
			    <div class="controls">
			    	<%= f.text_area :other, rows: 2, maxlength: 2000, class: "span6" %> 
			    </div>
			</div>
			
		    <%= f.submit "Post", :class => 'btn btn-primary'%>
		    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
		                parties_path, :class => 'btn' %>
	<% end %>
<% else %>
	<p>Sign in with <%= render 'shared/signin' %> to post a suggestion.</p>
<% end -%>

app/views/suggestions/_modal.html.erb
<div id="suggestion-modal" class="modal fade hide" data-keyboard="true">

	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3>Suggest new event</h3>
	</div>
	
	<div class="modal-body">

	<%= form_for @suggestion, :html => { :class => 'default' }, remote: true do |f| %>				
			<div id="suggestion_form_error" class="control-group hide">
				<span class="text-error">At least one of the fields needs to be filled out.</span>
			</div>
			
			<div class="control-group">
				<i class="icon-map-marker"></i> Location
		    	<%= f.text_area :location, rows: 2, maxlength: 2000, placeholder: "Location...", class: "span5" %> 
			</div>
			
			<div class="control-group">
				<i class="icon-music"></i> Music
		    	<%= f.text_area :music, rows: 2, maxlength: 2000, placeholder: "Music...", class: "span5" %> 
			</div>
			
			<div class="control-group">
				<i class="icon-star"></i> Games
		    	<%= f.text_area :games, rows: 2, maxlength: 2000, placeholder: "Games...", class: "span5" %> 
			</div>
			
			<div class="control-group">
				<i class="icon-glass"></i> Food/Drinks
		    	<%= f.text_area :food_drinks, rows: 2, maxlength: 2000, placeholder: "Food and drinks...", class: "span5" %> 
			</div>
			
			<div class="control-group">
				<i class="icon-list-alt"></i> Other
		    	<%= f.text_area :other, rows: 2, maxlength: 2000, placeholder: "Other...", class: "span5" %> 
			</div>
			
	</div>

	<div class="modal-footer">
		<%= f.submit "Post", 
			class: 'btn btn-primary more', 
			id: "suggestion-loading-msg",
			"data-loading-text"=>"loading...", 
			remote: true %>
		<button class="btn" data-dismiss="modal"> Cancel</button>
	</div>
	<% end %>
</div>

app/views/suggestions/_modal_form.html.erb
<%= form_for @suggestion, :html => { :class => 'form-horizontal' }, remote: true do |f| %>				
		<div id="suggestion_form_error" class="control-group hide">
			<div class="controls">
				<span class="text-error">At least one of the fields needs to be filled out.</span>
		   </div>
		</div>
		
		<div class="control-group">
	    	<%= f.text_area :location, rows: 2, maxlength: 2000, placeholder: "Location..." %> 
		</div>
		
		<div class="control-group">
	    	<%= f.text_area :music, rows: 2, maxlength: 2000, placeholder: "Suggest music..." %> 
		</div>
		
		<div class="control-group">
	    	<%= f.text_area :games, rows: 2, maxlength: 2000, placeholder: "Suggest new games..." %> 
		</div>
		
		<div class="control-group">
	    	<%= f.text_area :food_drinks, rows: 2, maxlength: 2000, placeholder: "Suggest food and drinks..." %> 
		</div>
		
		<div class="control-group">
	    	<%= f.text_area :other, rows: 2, maxlength: 2000, placeholder: "Anything else you want to add?" %> 
		</div>
		
		<div class="form-actions">
		    <%= f.submit "Suggest", :class => 'btn btn-primary' %>
		    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
		                parties_path, :class => 'btn' %>
		</div>
<% end %>

app/views/suggestions/_suggestion.html.erb
<article id="<%= suggestion.id %>" class="media suggestion">
	<% if current_user && admin_user? %>
		<%= link_to "×", suggestion, class: "close", method: :delete, remote: true %>
	<% end %>

	<div  class="collapse-link" data-toggle="collapse" data-target="#<%= suggestion.id %>-toggle">
		<div class="pull-left">
			<%= image_tag(suggestion.user.img_url, size: "40x40", class: "img-rounded") %>
		</div>

		<div class="media-body">
			<div class="media-header">
				<%= link_to suggestion.user.name, suggestion.user.profile_url %>
				<small class="muted"><%= time_ago_in_words(suggestion.created_at) %></small>
			</div>

			<% if !suggestion.location.nil? %>
				<p>
					<strong>Location</strong> - <%= suggestion.location %>
				</p>
			<% end %>

			<% if !suggestion.music.nil? %>
				<p>
					<strong>Music</strong> - <%= suggestion.music %>
				</p>
			<% end %>

			<% if !suggestion.games.nil? %>
				<p>
					<strong>Games</strong> - <%= suggestion.games %>
				</p>
			<% end %>

			<% if !suggestion.food_drinks.nil? %>
				<p>
					<strong>Food/Drinks</strong> - <%= suggestion.food_drinks %>
				</p>
			<% end %>

			<% if !suggestion.other.nil? %>
				<p>
					<strong>Other</strong> - <%= suggestion.other %>
				</p>
			<% end %>
		</div>
			
	</div>

	<div class="separator">
			<span id="vote_link">
				<% if current_user %>
					<% if suggestion.votes.include?(current_user.id) %>
						<%= link_to (image_tag "star.png", class: "star"),
							"#{suggestions_unstar_path}?suggestion=#{suggestion.id}", remote: true %> 
					<% else %>
						<%= link_to (image_tag "star_empty.png", class: "star"), 
							"#{suggestions_star_path}?suggestion=#{suggestion.id}", remote: true %> 
					<% end -%>	
				<% else %>
					<a rel="popover" data-placement="right" 
							data-content="<div class='text-center'><%= render 'shared/signin' %></div>"
							data-original-title="Sign in to vote:"><%= image_tag "star.png", class: "star" %></a>
				<% end -%>
			</span>

			<span id="vote_count_<%= suggestion.id %>"><%= suggestion.vote_counter %></span> 
			| 
			<a href="#" class="collapse-link gray" data-toggle="collapse" data-target="#<%= suggestion.id %>-toggle">
			  Comments (<span id="comment_count_<%= suggestion.id %>"><%= suggestion.comment_counter %></span>)
			</a>

			<span class="pull-right hide test" id="<%= suggestion.id %>-load-comments">				
				<% if suggestion.comments.count > 3 %>
					<span id="<%= suggestion.id %>-loading-msg" class="muted" "data-loading-text"="loading..." >showing </span>
					<% if suggestion.comments.count <= 50 %>
						<%= link_to("/comments?suggestion_id=#{suggestion.id}",
							remote: true,
							class: "suggestion-comments",
							id: "load_more_comments_#{suggestion.id}") do %>
							<span id="stat_bar_<%= suggestion.id %>"> 
							<span id="showing_<%= suggestion.id %>">3</span>/<span id="comment_total_<%= suggestion.id %>"><%= suggestion.comment_counter %></span>
							</span>        	
						<% end -%>
					<% else %>
						<%= link_to("/comments?suggestion_id=#{suggestion.id}&skip=#{suggestion.comments.count - 50 - 3}",
							remote: true,
							class: "suggestion-comments",
							id: "load_more_comments_#{suggestion.id}") do %>
							<span id="stat_bar_<%= suggestion.id %>"> 
							<span id="showing_<%= suggestion.id %>">3</span>/<span id="comment_total_<%= suggestion.id %>"><%= suggestion.comment_counter %></span>
							</span>
						<% end -%>
					<% end -%>
				<% end -%>
			</span>
	</div>
	
	<div id="<%= suggestion.id %>-toggle" class="collapse">
		<div id="dummy_<%= suggestion.id %>" class="comments"></div>

		<div id="<%= suggestion.id %>_comments" class="comments">
			<% if suggestion.comments.count > 0 %>
				<% get_comments_for_suggestion(suggestion).each do |comment| %>
					<%= render "comments/suggestion_comment", object: [suggestion, comment] %>
				<% end %>
			<% end %>
		</div>

		<div class="form">
			<% if current_user %>
				<%= render 'comments/suggestion_comment_form', object: suggestion %>
			<% else %>
				<a rel="popover" data-placement="right" 
							data-content="<div class='text-center'><%= render 'shared/signin' %></div>"
							data-original-title="Sign in with:">Sign in</a> to leave a comment
				
			<% end %>
		</div>
	</div>
</article>

app/views/suggestions/_suggestion_mini.html.erb
<article class="media">
	<div class="pull-left">
		<%= image_tag(object.user.img_url, size: "40x40", class: "img-rounded") %>
	</div>

	<div class="media-body">
		<div class="media-header">
			<%= link_to object.user.name, object.user.profile_url %>
			<small class="muted"><%= time_ago_in_words(object.created_at) %></small>
		</div>

		<% if !object.location.nil? %>
			<p>
				<i class="icon-map-marker"></i> <strong>Location</strong> - <%= object.location %>
			</p>
		<% end %>

		<% if !object.music.nil? %>
			<p>
				<i class="icon-music"></i> <strong>Music</strong> - <%= object.music %>
			</p>
		<% end %>

		<% if !object.games.nil? %>
			<p>
				<i class="icon-star"></i> <strong>Games</strong> - <%= object.games %>
			</p>
		<% end %>

		<% if !object.food_drinks.nil? %>
			<p>
				<i class="icon-glass"></i> <strong>Food/Drinks</strong> - <%= object.food_drinks %>
			</p>
		<% end %>

		<% if !object.other.nil? %>
			<p>
				<i class="icon-list-alt"></i> <strong>Other</strong> - <%= object.other %>
			</p>
		<% end %>
	</div>
	<div class="separator">	
			<%= image_tag "star.png", class: "star" %> 
			<%= object.vote_counter %><span class="muted"> | </span><%= pluralize object.comment_counter, "comment" %>
		</div>
</article>

app/views/suggestions/create.js.erb
<% if @suggestion.errors.empty? %>
	// $("#new_suggestion").fadeOut(100, function(){ $(this).remove();});
	$('#suggestion_form_error').hide()
	$('#suggestions').prepend("<%= escape_javascript(render @suggestion) %>")
	$("#suggestion-count").text("<%= @count %>")
	$('#suggestion-modal').modal('hide')
	clean_up()
	add_keydown_action("comment_content_<%= @suggestion.id %>", "post_button_<%= @suggestion.id %>")
<% else %>
	$('#suggestion_form_error').show()
<% end %>	

$("#suggestion-loading-msg").button('reset')

app/views/suggestions/destroy.js.erb
$('#<%= @suggestion.id %>').fadeOut(100, function(){ $(this).remove();});
$("#suggestion-count").text("<%= @count %>")

app/views/suggestions/edit.js.erb
<% if @suggestion.nil? %>
	alert("Something went wrong. Try reloading the page before voting again. <%= @test %>")
<% else %>
	$("#<%= @suggestion.id %> .well a img").attr("src", "/assets/star.png")
	$('#vote_count_<%= @suggestion.id %>').text('<%= @suggestion.vote_counter %>')
<% end %>

app/views/suggestions/index.html.erb
<div class="row">
	<div class="span7">
		<div class="pull-right fb-like visible-desktop" data-send="false" data-layout="button_count" data-width="450" data-show-faces="true"></div>
		<p class="lead">
			Have a great idea for a party but too busy to organize it all on your own? Suggest the party here and we just might 	make it a reality!
		</p>

		<p class="text-center">
			<% if current_user %>
				<% if @suggestions.count > 0 %>
					<button class="btn btn-primary btn-large hidden-phone" data-target="#suggestion-modal" data-toggle="modal" 
						data-keyboard="true">
						Suggest an event
					</button>

					<%= link_to "Suggest an event", new_suggestion_path, class: "btn btn-primary btn-large visible-phone" %>
				<% end -%>
			<% else %>
				<a class="btn btn-primary btn-large visible-phone" rel="popover" data-placement="bottom" 
					data-content="<div class='text-center'><%= render 'shared/signin' %></div>"
					data-original-title="Sign in with:">Suggest an event</a>
				<a class="btn btn-primary btn-large hidden-phone" rel="popover" data-placement="bottom" 
					data-content="<div class='text-center'><%= render 'shared/signin' %></div>"
					data-original-title="Sign in with:">Suggest an event</a>
			<% end -%>
		</p>

		<% if @suggestions.count == 0 %>	
			<% if current_user %>
				<%= render 'form' %>
			<% end -%>
		<% else %>

			<div class="row">
				<h4 class="span4">Suggestions (<span id="suggestion-count"><%= @suggestions.count %></span>)</h4>

				<% if @suggestions.count > 2 %>
					<div id="sort" class="sort dropdown visible-desktop pull-right">
						<span id="sort-loading-msg" class="hide muted">loading... </span>
						<a class="dropdown-toggle" id="sort" data-toggle="dropdown" href="#">Sort <b class="caret"></b></a>
						<ul class="dropdown-menu" aria-labelledby="sort">
							<li><%= link_to "Date", "#{suggestions_path}?sort=date", remote: true %></li>
					    	<li><%= link_to "Votes", "#{suggestions_path}?sort=votes", remote: true %></li>
					    	<li><%= link_to "Comments", "#{suggestions_path}?sort=comments", remote: true %></li>
				        </ul>
					</div>
				<% end %>
			</div>
			
						
			<div id="suggestions">
				<% if @suggestions.count > 0 %>
					<%= render @suggestions %>
				<% end %>
			</div>
					
			<p id="more_link">
				<% unless @done %>
					<%= link_to "More", "/suggestions?skip=#{@skip}", id: "more", class: "more", 
						"data-loading-text"=>"Loading...", remote: true %>
				<% end %>
			</p>
		<% end -%>

		<%= render "modal" %>
	</div>

	<aside class="span5 hidden-phone suggestions-sidebar aside suggestions-aside">
		<% if @upcoming.count > 0 %>
			<p class="lead muted">Upcoming events</p>
			<ul class="thumbnails">
				<% if @upcoming.count > 0 %>
					<% @upcoming.each do |event| %>
						<li><%= render 'parties/sidebar_party', object: [event, "x"] %></li>
					<% end -%>
				<% end %>
			</ul>
			
			<% if @upcoming.count > 3 %>
				<%= link_to "More", root_path %>
			<% end -%>

			<hr class="bs-docs-separator">
		<% end -%>

		<% if @previous.count > 0 %>
			<p class="lead muted">Previous events</p>
			<ul class="thumbnails">
				<% @previous.each do |event| %>
					<li><%= render 'parties/sidebar_party', object: [event, "x"] %></li>
				<% end -%>
			</ul>

			<% if @previous.count > 3 %>
				<%= link_to "More", root_path %>
			<% end -%>

			<hr class="bs-docs-separator">
		<% end -%>
	</aside>
</div>

app/views/suggestions/index.js.erb
<% if @replace %>
	$('#hidden_link').attr("href", "#")
	$('#suggestions').html("<%= escape_javascript(render @suggestions) %>")
<% else %>
	$('#suggestions').append("<%= escape_javascript(render @suggestions) %>")
<% end %>

<% if @sort %>
	var URI = "/suggestions?sort=<%= @sort %>&skip=<%= @skip %>"
	$("#sort-loading-msg").hide()
<% else %>
	var URI = "/suggestions?skip=<%= @skip %>"
<% end %>

<% if @done %>
	$("#more").remove()
	// $("#more").attr("href", "")
<% else %>
	if ($("#more").show().length == 0) {
		var more = $("<a id='more' class='hide' data-remote='true'>View more suggestions</a>")
		$("#more_link").append(more)
	}	
	$("#more").attr("href", URI)
	load_more_on_scroll()
<% end %>

fix_forms()
fix_suggestion_comment_loading_effect()
fix_collapse_links()

app/views/suggestions/new.html.erb
<%- model_class = Suggestion -%>

<h3>New suggestion</h3>

<%= render :partial => 'form' %>

app/views/suggestions/show.html.erb
<%- model_class = Suggestion -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:_type) %>:</strong></dt>
  <dd><%= @suggestion._type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:_id) %>:</strong></dt>
  <dd><%= @suggestion._id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @suggestion.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @suggestion.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @suggestion.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:music) %>:</strong></dt>
  <dd><%= @suggestion.music %></dd>
  <dt><strong><%= model_class.human_attribute_name(:games) %>:</strong></dt>
  <dd><%= @suggestion.games %></dd>
  <dt><strong><%= model_class.human_attribute_name(:food_drinks) %>:</strong></dt>
  <dd><%= @suggestion.food_drinks %></dd>
  <dt><strong><%= model_class.human_attribute_name(:other) %>:</strong></dt>
  <dd><%= @suggestion.other %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vote_counter) %>:</strong></dt>
  <dd><%= @suggestion.vote_counter %></dd>
  <dt><strong><%= model_class.human_attribute_name(:votes) %>:</strong></dt>
  <dd><%= @suggestion.votes %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment_counter) %>:</strong></dt>
  <dd><%= @suggestion.comment_counter %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              suggestions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_suggestion_path(@suggestion), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              suggestion_path(@suggestion),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/suggestions/star.js.erb
<% if @suggestion %>
	$("#<%= @suggestion.id %> #vote_link a").attr("href", "/suggestions/unstar?suggestion=<%= @suggestion.id %>")
	$("#<%= @suggestion.id %> #vote_link a img").attr("src", "/assets/star.png")
	$('#vote_count_<%= @suggestion.id %>').text('<%= @suggestion.vote_counter %>')
<% end %>

app/views/suggestions/unstar.js.erb
<% if @suggestion %>
	$("#<%= @suggestion.id %> #vote_link a").attr("href", "/suggestions/star?suggestion=<%= @suggestion.id %>")
	$("#<%= @suggestion.id %> #vote_link a img").attr("src", "/assets/star_empty.png")
	$('#vote_count_<%= @suggestion.id %>').text('<%= @suggestion.vote_counter %>')
<% end %>