config/routes.rb
Komanda::Application.routes.draw do
  root :to => 'parties#index'
  
  #match '/users' => 'static_pages#users'
  match '/stats' => 'static_pages#stats'

  match '/contact' => 'static_pages#contact'
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', :as => :signout
  
  match '/shares' => 'shares#index'

  match '/parties/rate', :controller => 'parties', :action => 'rate'
  match '/parties/join', :controller => 'parties', :action => 'join'
  match '/parties/unjoin', :controller => 'parties', :action => 'unjoin'

  match '/suggestions/star', :controller => 'suggestions', :action => 'star'
  match '/suggestions/unstar', :controller => 'suggestions', :action => 'unstar'

  resources :shares
  resources :comments

  resources :parties do
    resources :comments
  end
  
  resources :suggestions do
    resources :comments
  end
end

app/views/layouts/_footer.html.erb
<footer id="footer">
<div class="container">
<div class="row">
<div class="offset1 span10">
<%= link_to "Contact", "/contact" %> <span class="muted"> | </span> 
<a href="#donate-modal" data-toggle="modal" data-keyboard="true">Donate</a>
</div>
</div>

</div>
<div id="donate-modal" class="modal fade hide" data-keyboard="true">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<h3>Make a donation</h3>
</div>

<div class="modal-body">
<p>Give us all your money muahahaha!</p>
<%= render 'shared/donate' %>
</div>

</div>
</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">     
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>

	      <%= link_to(root_path, class: "brand") do %>
	      	<%= image_tag "star.png" %><span class="red">Komanda</span>
	      <% end %>
	      <% link_to image_tag("komanda_clean.png", size: "130x00"), root_path, class: "brand" %>
	 
	      <div class="nav-collapse collapse">
	      	<div class="offset4 visible-desktop">
		        <ul class="nav">
		        	<li class="first <%= "_active" unless !parties_controller? %>"><%= link_to "Events", parties_path  %></li>
					<li class="<%= "_active" unless !suggestions_controller? %>"><%= link_to "Suggestions", suggestions_path  %></li>
					<!-- <li class="<%= "_active" unless !shares_controller? %>"><%= link_to "Share", shares_path  %></a></li> -->
					<li>
						<a rel="popover" data-placement="bottom" 
							data-content="Work in progress..."
							data-original-title="Warning!">
							Share</a>
					</li>
					<li>
						<a rel="popover" data-placement="bottom" 
							data-content="Work in progress..."
							data-original-title="Warning">
							K-stuff</a>
					</li>
					<% if current_user && admin_user? %>
						<li><%= link_to "Stats", stats_path %></li>
					<% end -%>
		        </ul>
		    </div>
		    <div class="visible-phone">
			    <ul class="nav">
		        	<li class="<%= "active" unless !parties_controller? %>"><%= link_to "Events", parties_path  %></li>
					<li class="<%= "active" unless !suggestions_controller? %>"><%= link_to "Suggestions", suggestions_path  %></li>
					<!-- <li class="<%= "active" unless !shares_controller? %>"><%= link_to "Share", shares_path  %></li> -->
					<li>
						<a rel="popover" data-placement="bottom" 
							data-content="Work in progress..."
							data-original-title="Warning!">
							Share</a>
					</li>
					<li>
						<a rel="popover" data-placement="bottom" 
							data-content="Work in progress..."
							data-original-title="Warning!">
							K-stuff</a>
					</li>
					<% if current_user && admin_user? %>
						<li><%= link_to "Stats", stats_path %></li>
					<% end -%>
		        </ul>
	       </div>
		    <ul class="nav pull-right">
	        	<li class="dropdown">
					<% if current_user %>
						<a href="#" class="dropdwon-toggle" data-toggle="dropdown">
							<%= image_tag(current_user.img_url, size: "20x20") %>
							<%= current_user.name %>
							<b class="caret"></b>
						</a>

						<ul class="dropdown-menu">
							<li><%= link_to "Sign out", signout_path %></li>
						</ul>
					<% else %>
						<a href="#" class="dropdwon-toggle" data-toggle="dropdown">
							Sign in
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><a href='/auth/twitter' class='auth_provider'>Twitter</a></li>
							<li><a href='/auth/facebook' class='auth_provider'>Facebook</a></li>
							<li><a href='/auth/google_oauth2' class='auth_provider'>Google</a></li>
						</ul>
					<% end -%>
				</li>
	        </ul>
	      </div>
	 
	    </div>
	  </div>
	</nav>
</header>
<!-- <header>

	<nav class="container">
		<div class="row">
			<div class="span2">
				<%= link_to image_tag("komanda_clean.png", size: "130x00"), root_path %>
			</div>

			<div class="span6 offset1">
				<ul class="text-center">
	              <li class="<%= "active" unless !parties_controller? %>"><%= link_to "Events", parties_path  %></li>
	              <li class="<%= "active" unless !suggestions_controller? %>"><%= link_to "Suggestions", suggestions_path  %></li>
	              <li class="<%= "active" unless !shares_controller? %>"><%= link_to "Share", shares_path  %></li>
				  <li><a href="#donate-modal" data-toggle="modal" data-keyboard="true">Donate</a></li>
	            </ul>
			</div>

			<div class="span3 pull-right">
				<ul class="text-right">
					<% if current_user %>
						<% if admin_user? %>
							<li><%= link_to "Stats", stats_path %></li>
						<% end -%>
						<%= render 'shared/user' %>
					
					<% else %>
						<li><a rel="popover" data-placement="bottom" 
							data-content="<div class='text-center'><%= render 'shared/signin' %></div>"
							data-original-title="Sign in with:">Sign in</a></li>
					<% end %>
				</ul>
			</div>
		</div> 
	</nav>			
</header> -->



<%# render 'shared/images' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Komanda" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    
  </head>
  <body>
  	<%= render 'layouts/header' %>
  	
  	<div id="wrap">
	   	<section class="container margin-top">	
			<!-- <div class="row-fluid">
				<div class="span1 bg text-center">1</div>
				<div class="span1 bg text-center">2</div>
				<div class="span1 bg text-center">3</div>
				<div class="span1 bg text-center">4</div>
				<div class="span1 bg text-center">5</div>
				<div class="span1 bg text-center">6</div>
				<div class="span1 bg text-center">7</div>
				<div class="span1 bg text-center">8</div>
				<div class="span1 bg text-center">9</div>
				<div class="span1 bg text-center">10</div>
				<div class="span1 bg text-center">11</div>
				<div class="span1 bg text-center">12</div>
			</div> -->
			
			<%= yield %>
			
	   	</section>

	   	<div id="push"></div>
	</div>

   	<%= render 'layouts/footer' %>
	  


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
	
	<!-- Script for _form.html.erb for comments. Allows to post comments by
		 hitting return key! -->
	<script>
		// for parties
		fix_comment_form();
		function fix_comment_form() {
			$("#comment_content").keydown(function(e) { 
				if (13 == e.keyCode)
					$("#post_button").click()
			});
		}

		// share form
		add_keydown_action("share_content", "post_button")
		
		// for suggestions
		fix_forms();
		
		function fix_forms() {
			var suggestions = $(".suggestion");
			var comment_forms = $(".comment_content");
			var post_buttons = $(".post_button");

			for (var i=0; i < comment_forms.length; i++) {	
				var suggestion_id = $(suggestions[i]).attr("id");
				var comment_form_id = "comment_content_" + suggestion_id;
				var button_id = "post_button_" + suggestion_id;
				
				$(comment_forms[i]).attr("id", comment_form_id);
				$(post_buttons[i]).attr("id", button_id);
				
				add_keydown_action(comment_form_id, button_id)
			}
		}

		function add_keydown_action(id1, id2) {
			$("#" + id1).keydown(function (e) {
				if (e.keyCode == 13)
					$("#" + id2).click()
			});
		}
		
		// drop-down sort for suggestions 
		fix_sort()

		function fix_sort() {
			$("#sort li").click(function() {
				$("#sort-loading-msg").show()
			})
		}

		// Auto-load more at the bottom of the screen	
		load_more_on_scroll()
		
		function load_more_on_scroll() {
			<% if params[:controller] == "parties" && params[:action] == "show" %>
				$("#index").scroll(function() {
					if ($("#index").scrollTop() >= 100) {
						$("#index").unbind('scroll');
						$("#more").click();
				   }
				})
			<% else %>
				$(window).scroll(function() {
					if($(window).scrollTop() + $(window).height() > $(document).height()-100) {
						$(window).unbind('scroll');
				     	$("#more").click();
				   }
				})
			<% end -%>
		}
		
		// Google analytics
		var _gaq = _gaq || [];
	  	_gaq.push(['_setAccount', 'UA-36057894-1']);
	  	_gaq.push(['_trackPageview']);

	  	(function() {
		   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();

		function clean_up() {
			$("#suggestion_location").attr("value", "")
			$("#suggestion_music").attr("value", "")
			$("#suggestion_games").attr("value", "")
			$("#suggestion_food_drinks").attr("value", "")
			$("#suggestion_other").attr("value", "")

			$('#collapseOne').collapse('toggle')
		}

		// for picture-pane

		function fix_show_pictures_link() {
			if ($("#show_pictures").length > 0) {
				
				$("#show_pictures").click(function(e) {
					e.preventDefault()
					// $("#pics_loading_msg").button("loading")
					show_all_images()
				})
			} 
		}

		function show_all_images() {
			var imgs = $("#pictures").children()
			var i = 9

			function show_next_image() {
				if (i < imgs.length) {
		      		$(imgs[i]).fadeIn(100)
		      		i++
			    } else {
			    	clearInterval(intervalID)
			    	$("#show_pictures").remove()
			    	$("#pics_loading_msg").button("reset").html("showing " + imgs.length + "/" + imgs.length)
			    }
			}

			var intervalID = setInterval(show_next_image, 10)
		}

		// attach links to photos
		fix_pictures_modal();

		function fix_pictures_modal() {
			var imgs = []
			var items = $("#pictures").children()

			for (i = 0; i < items.length; i++) {
				imgs[i] = $(items[i]).find("img").first().attr("src")
			}

			for (var i=0; i < items.length; i++) {
				$(items[i]).find("img").first().click(function() {
					$("#modal-picture").attr("src", $(this).attr("src"));

					var index = imgs.indexOf($(this).attr("src"))
					$("#picture_index").text(index + 1); 
					$("#modal-picture").attr("src", $(this).attr("src"));  

					$("#next-button").click(function() {
						$("#modal-picture").attr("src", imgs[(index + 1)%imgs.length]); 
						index++;
						$("#picture_index").text(index % imgs.length + 1);
					});

					$("#prev-button").click(function() {
						if (index == 0) {
							index = imgs.length;
							$("#modal-picture").attr("src", imgs[index - 1]); 
						}
						else {
							$("#modal-picture").attr("src", imgs[(index - 1)%imgs.length]); 
						}
						index--;
						$("#picture_index").text(index % imgs.length + 1);
					});
				})
				$("modal-picture").modal('toggle')
			}
		}

		<% if @party %>
			function update_party_links(party_id) {
				var a = $("#index article a")

				for (var i=0; i<a.length; i++) {
					var url = $(a[i]).attr("href").split("=")[0];
					$(a[i]).attr("href", url + "=" + party_id)
				}
			}
		<% end %>

		/* for rating events */
		<% if params[:controller] == "parties" && params[:action] == "show" %>
			add_rating_on_hover()
			fix_show_pictures_link()
		<% end -%>

		function add_rating_on_hover() {
			$("#rate a").mouseover(function() {
				$(this).children().first().attr("src", "/assets/star.png")
				var prev = $(this).prevAll();
				var next = $(this).nextAll();

				for (var i = 0; i < prev.length; i++) {
					$(prev[i]).children().first().attr("src", "/assets/star.png")
				}

				for (var j=0; j<next.length; j++) {
					$(next[j]).children().first().attr("src", "/assets/star_empty.png")
				}
			})

			$("#rate").mouseleave(function() {
				set_rating()
			})
		}

		function set_rating() {	
			var rating = parseInt($("#rate").attr("val"))

			var links = $("#rate").children()

			for (var i = 0; i < rating; i++)
				$(links[i]).children().first().attr("src", "/assets/star.png")

			for (var i = rating; i < 5; i++)
				$(links[i]).children().first().attr("src", "/assets/star_empty.png")	
		}

		facebook_like()

		function facebook_like() {
			(function(d, s, id) {
			  var js, fjs = d.getElementsByTagName(s)[0];
			  if (d.getElementById(id)) return;
			  js = d.createElement(s); js.id = id;
			  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=399921200081202";
			  fjs.parentNode.insertBefore(js, fjs);
			}(document, 'script', 'facebook-jssdk'));
		}

		/* add loading effect to all "more" buttons */
		add_loading_effect()

		function add_loading_effect() {	
			$(".more").click(function() {
				var b = $(this)
				b.button('loading')
			})
		}

		add_comments_loading_effect()

		function add_comments_loading_effect() {
			$("#more_comments_link").click(function() {
				$("#loading-msg").button("loading")
			})
		}

		add_pics_loading_effect()
		
		function add_pics_loading_effect() {
			$("#show_pictures").click(function() {
				$("#pics_loading_msg").button("loading")
			})
		}

		fix_suggestion_comment_loading_effect()

		function fix_suggestion_comment_loading_effect() {
			$(".suggestion-comments").click(function() {
				$(this).siblings().button("loading")
			})
		}

		fix_collapse_links()

		function fix_collapse_links() {
			$(".collapse-link").click(function(e) {
				e.preventDefault()
				$(this).parent().find(".test").toggle()
			})
		}

		fix_scroll_top()
		function fix_scroll_top() {
			$(".scroll").click(function() {
				$('html, body').animate({scrollTop:0}, 'slow');	
			})
		}
	</script>

  </body>
</html>

app/views/layouts/fluid.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Komanda" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Komanda</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
             <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>